In [25]:
from inspect import FrameInfo
from google.colab import drive
drive.mount('/content/drive')

import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.font_manager as fm

font_path = '/content/drive/MyDrive/kwukdt/data-analysis/data-pre-processing/NanumGothic.ttf'

fm.fontManager.addfont(font_path)
mpl.rc('font', family = 'NanumGothic')
plt.rcParams['axes.unicode_minus'] = False

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

titanic = pd.read_csv('/content/drive/MyDrive/kwukdt/data-analysis/data-pre-processing/train.csv')
print(titanic.shape)
titanic.head()

(891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [27]:
from pathlib import Path
import os

passengers = titanic[['Survived', 'Sex', 'Age', 'Name']].copy()
passengers.insert(0, 'passenger_id', range(1, len(titanic)+1))

tickets = titanic[['Fare', 'Embarked', 'Pclass']].copy()
tickets.insert(0, 'passenger_id', range(1, len(titanic)+1))
tickets.columns = ['passenger_id', 'fare', 'embarked', 'pclass']

class_info = pd.DataFrame({
    'pclass' : [1, 2, 3],
    'class_name' : ['First Class', 'Second Class', 'Third Class'],
    'class_desc' : ['최상위 등급', '중간 등급', '일반 등급'],
    'base_fare' : [50.0, 20.0, 8.0]
})

port_info = pd.DataFrame({
    'embarked' : ['S', 'C', 'Q'],
    'port_name' : ['Southhampton', 'Cherbourg', 'Queenstown'],
    'country' : ['영국', '프랑스', '아일랜드']
})

In [28]:
output_dir = '/content/drive/MyDrive/kwukdt/data-analysis/data-pre-processing/eda/processed-data'
os.makedirs(output_dir, exist_ok=True)

passengers.to_csv(os.path.join(output_dir, 'passenger.csv'), index=False)
tickets.to_csv(os.path.join(output_dir, 'tickets.csv'), index=False)
class_info.to_csv(os.path.join(output_dir, 'class_info.csv'), index=False)
port_info.to_csv(os.path.join(output_dir, 'port_info.csv'), index=False)

In [29]:
output_dir = '/content/drive/MyDrive/kwukdt/data-analysis/data-pre-processing/eda/processed-data'

passengers = pd.read_csv(os.path.join(output_dir, 'passenger.csv'))
tickets = pd.read_csv(os.path.join(output_dir, 'tickets.csv'))
class_info = pd.read_csv(os.path.join(output_dir, 'class_info.csv'))
port_info = pd.read_csv(os.path.join(output_dir, 'port_info.csv'))

In [30]:
# concat()
p1 = passengers[passengers['passenger_id'].isin(tickets[tickets['pclass'] == 1]['passenger_id'])]
p1

,passenger_id,Survived,Sex,Age,Name
1,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
3,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
6,7,0,male,54.0,"McCarthy, Mr. Timothy J"
11,12,1,female,58.0,"Bonnell, Miss. Elizabeth"
23,24,1,male,28.0,"Sloper, Mr. William Thompson"
...,...,...,...,...,...
871,872,1,female,47.0,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)"
872,873,0,male,33.0,"Carlsson, Mr. Frans Olof"
879,880,1,female,56.0,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)"
887,888,1,female,19.0,"Graham, Miss. Margaret Edith"
889,890,1,male,26.0,"Behr, Mr. Karl Howell"

In [31]:
p2 = passengers[passengers['passenger_id'].isin(tickets[tickets['pclass'] == 2]['passenger_id'])]
p2

,passenger_id,Survived,Sex,Age,Name
9,10,1,female,14.0,"Nasser, Mrs. Nicholas (Adele Achem)"
15,16,1,female,55.0,"Hewlett, Mrs. (Mary D Kingcome)"
17,18,1,male,NaN,"Williams, Mr. Charles Eugene"
20,21,0,male,35.0,"Fynney, Mr. Joseph J"
21,22,1,male,34.0,"Beesley, Mr. Lawrence"
...,...,...,...,...,...
866,867,1,female,27.0,"Duran y More, Miss. Asuncion"
874,875,1,female,28.0,"Abelson, Mrs. Samuel (Hannah Wizosky)"
880,881,1,female,25.0,"Shelley, Mrs. William (Imanita Parrish Hall)"
883,884,0,male,28.0,"Banfield, Mr. Frederick James"
886,887,0,male,27.0,"Montvila, Rev. Juozas"

In [32]:
p3 = passengers[passengers['passenger_id'].isin(tickets[tickets['pclass'] == 3]['passenger_id'])]
p3

,passenger_id,Survived,Sex,Age,Name
0,1,0,male,22.0,"Braund, Mr. Owen Harris"
2,3,1,female,26.0,"Heikkinen, Miss. Laina"
4,5,0,male,35.0,"Allen, Mr. William Henry"
5,6,0,male,NaN,"Moran, Mr. James"
7,8,0,male,2.0,"Palsson, Master. Gosta Leonard"
...,...,...,...,...,...
882,883,0,female,22.0,"Dahlberg, Miss. Gerda Ulrika"
884,885,0,male,25.0,"Sutehall, Mr. Henry Jr"
885,886,0,female,39.0,"Rice, Mrs. William (Margaret Norton)"
888,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie"""
890,891,0,male,32.0,"Dooley, Mr. Patrick"

In [33]:
result_raw = pd.concat([p1, p2, p3], ignore_index=True)
result_raw

,passenger_id,Survived,Sex,Age,Name
0,2,1,female,38.0,"Cumings, Mrs. John Bradley (Florence Briggs Th..."
1,4,1,female,35.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)"
2,7,0,male,54.0,"McCarthy, Mr. Timothy J"
3,12,1,female,58.0,"Bonnell, Miss. Elizabeth"
4,24,1,male,28.0,"Sloper, Mr. William Thompson"
...,...,...,...,...,...
886,883,0,female,22.0,"Dahlberg, Miss. Gerda Ulrika"
887,885,0,male,25.0,"Sutehall, Mr. Henry Jr"
888,886,0,female,39.0,"Rice, Mrs. William (Margaret Norton)"
889,889,0,female,NaN,"Johnston, Miss. Catherine Helen ""Carrie"""
890,891,0,male,32.0,"Dooley, Mr. Patrick"

In [34]:
df_a = pd.DataFrame({
    'passenger_id' : [1, 2, 3],
    'name' : ['Alice', 'Bob', 'Carel'],
    'age' : [29, 35, 24]
})
df_a

   passenger_id   name  age
0             1  Alice   29
1             2    Bob   35
2             3  Carel   24

In [35]:
df_b = pd.DataFrame({
    'passenger_id' : [4, 5, 6],
    'name' : ['Dave', 'Eve', 'Frank'],
    'ticket_num' : ['A123', 'B456', 'C789']
})
df_b

   passenger_id   name ticket_num
0             4   Dave       A123
1             5    Eve       B456
2             6  Frank       C789

In [36]:
result_outer = pd.concat([df_a, df_b], ignore_index=True, join='outer')
result_outer

   passenger_id   name   age ticket_num
0             1  Alice  29.0        NaN
1             2    Bob  35.0        NaN
2             3  Carel  24.0        NaN
3             4   Dave   NaN       A123
4             5    Eve   NaN       B456
5             6  Frank   NaN       C789

In [37]:
base_info = passengers[['passenger_id', 'Name', 'Age']].head(5).reset_index(drop=True)
base_info

   passenger_id                                               Name   Age
0             1                            Braund, Mr. Owen Harris  22.0
1             2  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2             3                             Heikkinen, Miss. Laina  26.0
3             4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4             5                           Allen, Mr. William Henry  35.0

In [38]:
print("tickets 데이터프레임 (일부):")
display(tickets.head())

print("\nclass_info 데이터프레임:")
display(class_info)

# inner join
merged_inner = pd.merge(tickets, class_info, on='pclass', how='inner')
print("\n1. Inner Join (공통 pclass):")
display(merged_inner.head())

# left join
merged_left = pd.merge(tickets, class_info, on='pclass', how='left')
print("\n2. Left Join (tickets 기준):")
display(merged_left.head())

# right join
merged_right = pd.merge(tickets, class_info, on='pclass', how='right')
print("\n3. Right Join (class_info 기준):")
display(merged_right)

# outer join
merged_outer = pd.merge(tickets, class_info, on='pclass', how='outer')
print("\n4. Outer Join (모든 pclass):")
display(merged_outer.head())

tickets 데이터프레임 (일부):

   passenger_id     fare embarked  pclass
0             1   7.2500        S       3
1             2  71.2833        C       1
2             3   7.9250        S       3
3             4  53.1000        S       1
4             5   8.0500        S       3

class_info 데이터프레임:

   pclass    class_name class_desc  base_fare
0       1   First Class     최상위 등급       50.0
1       2  Second Class      중간 등급       20.0
2       3   Third Class      일반 등급        8.0

1. Inner Join (공통 pclass):

   passenger_id     fare embarked  pclass   class_name class_desc  base_fare
0             1   7.2500        S       3  Third Class      일반 등급        8.0
1             2  71.2833        C       1  First Class     최상위 등급       50.0
2             3   7.9250        S       3  Third Class      일반 등급        8.0
3             4  53.1000        S       1  First Class     최상위 등급       50.0
4             5   8.0500        S       3  Third Class      일반 등급        8.0

2. Left Join (tickets 기준):

   passenger_id     fare embarked  pclass   class_name class_desc  base_fare
0             1   7.2500        S       3  Third Class      일반 등급        8.0
1             2  71.2833        C       1  First Class     최상위 등급       50.0
2             3   7.9250        S       3  Third Class      일반 등급        8.0
3             4  53.1000        S       1  First Class     최상위 등급       50.0
4             5   8.0500        S       3  Third Class      일반 등급        8.0

3. Right Join (class_info 기준):

     passenger_id     fare embarked  pclass   class_name class_desc  base_fare
0               2  71.2833        C       1  First Class     최상위 등급       50.0
1               4  53.1000        S       1  First Class     최상위 등급       50.0
2               7  51.8625        S       1  First Class     최상위 등급       50.0
3              12  26.5500        S       1  First Class     최상위 등급       50.0
4              24  35.5000        S       1  First Class     최상위 등급       50.0
..            ...      ...      ...     ...          ...        ...        ...
886           883  10.5167        S       3  Third Class      일반 등급        8.0
887           885   7.0500        S       3  Third Class      일반 등급        8.0
888           886  29.1250        Q       3  Third Class      일반 등급        8.0
889           889  23.4500        S       3  Third Class      일반 등급        8.0
890           891   7.7500        Q       3  Third Class      일반 등급        8.0

[891 rows x 7 columns]

4. Outer Join (모든 pclass):

   passenger_id     fare embarked  pclass   class_name class_desc  base_fare
0             2  71.2833        C       1  First Class     최상위 등급       50.0
1             4  53.1000        S       1  First Class     최상위 등급       50.0
2             7  51.8625        S       1  First Class     최상위 등급       50.0
3            12  26.5500        S       1  First Class     최상위 등급       50.0
4            24  35.5000        S       1  First Class     최상위 등급       50.0

In [39]:
df_passenger_id_diff = passengers[['passenger_id', 'Name', 'Sex']].copy()
df_passenger_id_diff.columns = ['p_id', 'Name', 'Sex']
df_tickets_id_diff = tickets[['passenger_id', 'fare', 'embarked']].copy()

print("df_passenger_id_diff (p_id 열 사용):")
display(df_passenger_id_diff.head())

print("\ndf_tickets_id_diff (passenger_id 열 사용):")
display(df_tickets_id_diff.head())

merged_diff_cols = pd.merge(
    df_passenger_id_diff, df_tickets_id_diff,
    left_on='p_id', right_on='passenger_id',
    how='left'
)

print("\n다른 이름의 열(p_id, passenger_id)을 기준으로 병합 (Left Merge):")
display(merged_diff_cols.head())

merged_diff_cols_cleaned = merged_diff_cols.drop(columns=['passenger_id'])
print("\n병합 후 중복 키 열 제거:")
display(merged_diff_cols_cleaned.head())

df_passenger_id_diff (p_id 열 사용):

   p_id                                               Name     Sex
0     1                            Braund, Mr. Owen Harris    male
1     2  Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2     3                             Heikkinen, Miss. Laina  female
3     4       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4     5                           Allen, Mr. William Henry    male

df_tickets_id_diff (passenger_id 열 사용):

   passenger_id     fare embarked
0             1   7.2500        S
1             2  71.2833        C
2             3   7.9250        S
3             4  53.1000        S
4             5   8.0500        S

다른 이름의 열(p_id, passenger_id)을 기준으로 병합 (Left Merge):

,p_id,Name,Sex,passenger_id,fare,embarked
0,1,"Braund, Mr. Owen Harris",male,1,7.2500,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,2,71.2833,C
2,3,"Heikkinen, Miss. Laina",female,3,7.9250,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,4,53.1000,S
4,5,"Allen, Mr. William Henry",male,5,8.0500,S

병합 후 중복 키 열 제거:

,p_id,Name,Sex,fare,embarked
0,1,"Braund, Mr. Owen Harris",male,7.2500,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,71.2833,C
2,3,"Heikkinen, Miss. Laina",female,7.9250,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,53.1000,S
4,5,"Allen, Mr. William Henry",male,8.0500,S

In [40]:
df_left_idx = pd.DataFrame({'value_l': ['A', 'B', 'C']},
                             index=[0, 1, 2])
df_right_idx = pd.DataFrame({'value_r': [10, 20, 30]},
                              index=[2, 0, 1]) # 인덱스 순서가 다름

print("왼쪽 데이터프레임 (인덱스 기준):")
display(df_left_idx)

print("\n오른쪽 데이터프레임 (인덱스 기준):")
display(df_right_idx)

merged_by_index = pd.merge(
    df_left_idx, df_right_idx,
    left_index=True, right_index=True,
    how='inner'
)

print("\n인덱스를 기준으로 병합된 데이터프레임 (Inner Merge):")
display(merged_by_index)

왼쪽 데이터프레임 (인덱스 기준):

  value_l
0       A
1       B
2       C

오른쪽 데이터프레임 (인덱스 기준):

   value_r
2       10
0       20
1       30

인덱스를 기준으로 병합된 데이터프레임 (Inner Merge):

  value_l  value_r
0       A       20
1       B       30
2       C       10

In [41]:
print("passengers 데이터프레임 (일부):")
display(passengers[['passenger_id', 'Name']].head())

print("\ntickets 데이터프레임 (일부):")
display(tickets[['passenger_id', 'fare', 'pclass']].head())

# 1:1 병합
merged_1_to_1 = pd.merge(passengers[['passenger_id', 'Name']],
                         tickets[['passenger_id', 'fare', 'pclass']],
                         on='passenger_id',
                         how='inner')

print("\n1:1 병합 결과 (inner join):")
display(merged_1_to_1.head())
print(f"원래 passengers 행 수: {len(passengers)}")
print(f"원래 tickets 행 수: {len(tickets)}")
print(f"병합된 데이터프레임 행 수: {len(merged_1_to_1)}")

assert merged_1_to_1['passenger_id'].is_unique, "passenger_id가 고유하지 않습니다!"

passengers 데이터프레임 (일부):

   passenger_id                                               Name
0             1                            Braund, Mr. Owen Harris
1             2  Cumings, Mrs. John Bradley (Florence Briggs Th...
2             3                             Heikkinen, Miss. Laina
3             4       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4             5                           Allen, Mr. William Henry

tickets 데이터프레임 (일부):

   passenger_id     fare  pclass
0             1   7.2500       3
1             2  71.2833       1
2             3   7.9250       3
3             4  53.1000       1
4             5   8.0500       3

1:1 병합 결과 (inner join):

,passenger_id,Name,fare,pclass
0,1,"Braund, Mr. Owen Harris",7.2500,3
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",71.2833,1
2,3,"Heikkinen, Miss. Laina",7.9250,3
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",53.1000,1
4,5,"Allen, Mr. William Henry",8.0500,3

원래 passengers 행 수: 891
원래 tickets 행 수: 891
병합된 데이터프레임 행 수: 891

In [42]:
print("tickets 데이터프레임 (pclass 분포):")
display(tickets['pclass'].value_counts().sort_index())

print("\nclass_info 데이터프레임:")
display(class_info)

# n:1 병합
merged_n_to_1 = pd.merge(tickets[['passenger_id', 'pclass', 'fare']],
                         class_info[['pclass', 'class_name', 'base_fare']],
                         on='pclass',
                         how='inner')

print("\nn:1 병합 결과 (inner join):")
display(merged_n_to_1.head())

print(f"원래 tickets 행 수: {len(tickets)}")
print(f"병합된 데이터프레임 행 수: {len(merged_n_to_1)}")
assert len(merged_n_to_1) == len(tickets), "병합 후 행 수가 예상과 다릅니다!"

tickets 데이터프레임 (pclass 분포):

pclass
1    216
2    184
3    491
Name: count, dtype: int64

class_info 데이터프레임:

   pclass    class_name class_desc  base_fare
0       1   First Class     최상위 등급       50.0
1       2  Second Class      중간 등급       20.0
2       3   Third Class      일반 등급        8.0

n:1 병합 결과 (inner join):

   passenger_id  pclass     fare   class_name  base_fare
0             1       3   7.2500  Third Class        8.0
1             2       1  71.2833  First Class       50.0
2             3       3   7.9250  Third Class        8.0
3             4       1  53.1000  First Class       50.0
4             5       3   8.0500  Third Class        8.0

원래 tickets 행 수: 891
병합된 데이터프레임 행 수: 891

In [43]:
df_products = pd.DataFrame({
    'product_id': [1, 2, 3, 1, 2],
    'product_name': ['Apple', 'Banana', 'Cherry', 'Apple', 'Banana'],
    'category_code': ['F', 'F', 'F', 'S', 'D'] # F:과일, S:간식, D:음료
})

df_categories = pd.DataFrame({
    'category_code': ['F', 'F', 'S', 'D', 'D'],
    'feature': ['Sweet', 'Healthy', 'Crunchy', 'Cold', 'Fizzy']
})

print("df_products (category_code 중복):")
display(df_products)

print("\ndf_categories (category_code 중복):")
display(df_categories)

# n:n 병합
merged_n_to_n = pd.merge(df_products, df_categories, on='category_code', how='inner')

print("\nn:n 병합 결과 (inner join):")
display(merged_n_to_n)

print(f"원래 df_products 행 수: {len(df_products)}")
print(f"원래 df_categories 행 수: {len(df_categories)}")
print(f"병합된 데이터프레임 행 수: {len(merged_n_to_n)}")

assert len(merged_n_to_n) == 9, f"n:n 병합 후 행 수가 예상과 다릅니다! 예상: 9, 실제: {len(merged_n_to_n)}"

df_products (category_code 중복):

   product_id product_name category_code
0           1        Apple             F
1           2       Banana             F
2           3       Cherry             F
3           1        Apple             S
4           2       Banana             D

df_categories (category_code 중복):

  category_code  feature
0             F    Sweet
1             F  Healthy
2             S  Crunchy
3             D     Cold
4             D    Fizzy

n:n 병합 결과 (inner join):

   product_id product_name category_code  feature
0           1        Apple             F    Sweet
1           1        Apple             F  Healthy
2           2       Banana             F    Sweet
3           2       Banana             F  Healthy
4           3       Cherry             F    Sweet
5           3       Cherry             F  Healthy
6           1        Apple             S  Crunchy
7           2       Banana             D     Cold
8           2       Banana             D    Fizzy

원래 df_products 행 수: 5
원래 df_categories 행 수: 5
병합된 데이터프레임 행 수: 9

In [44]:
data_dir = 'temp_sales_data'
os.makedirs(data_dir, exist_ok=True)

df_jan = pd.DataFrame({
    'Date': ['2023-01-01', '2023-01-02'],
    'Product': ['A', 'B'],
    'Sales': [100, 150]
})
df_jan.to_csv(os.path.join(data_dir, 'sales_202301.csv'), index=False)

df_feb = pd.DataFrame({
    'Date': ['2023-02-01', '2023-02-02'],
    'Product': ['C', 'A'],
    'Sales': [200, 120]
})
df_feb.to_csv(os.path.join(data_dir, 'sales_202302.csv'), index=False)

print(f"{data_dir} 디렉토리에 두 개의 CSV 파일이 생성되었습니다.")

temp_sales_data 디렉토리에 두 개의 CSV 파일이 생성되었습니다.

In [45]:
import pandas as pd
from pathlib import Path

files = list(Path(data_dir).glob('sales_*.csv'))

print("찾은 파일 목록:")
for f in files:
    print(f)

dfs = [pd.read_csv(f) for f in files]

df_all = pd.concat(dfs, ignore_index=True)

print("\n통합된 데이터프레임 (df_all):")
display(df_all)

찾은 파일 목록:
temp_sales_data/sales_202301.csv
temp_sales_data/sales_202302.csv

통합된 데이터프레임 (df_all):

         Date Product  Sales
0  2023-01-01       A    100
1  2023-01-02       B    150
2  2023-02-01       C    200
3  2023-02-02       A    120