In [21]:
import numpy as np
import pandas as pd

In [22]:
df = pd.DataFrame([
    ["김", 80, 20 , "여성"],
    ["이", 92, 22 , "여성"],
    ["박", 76, 27 , "남성"],
    ["최", 88, 39 , "여성"],
    ["장", 64, 14 , "남성"]],
    columns=["이름", "점수", "나이", "성별"]
)

In [23]:
display(df)

  이름  점수  나이  성별
0  김  80  20  여성
1  이  92  22  여성
2  박  76  27  남성
3  최  88  39  여성
4  장  64  14  남성

In [25]:
print("DataFrame 구성:")
print(df.shape)
print("\nDataFrame 열:")
print(df.columns)
print("\nDataFrame 데이터 유형:")
print(df.dtypes)
print("\nDataFrame 정보:")
df.info()
print("\n처음 5개 행:")
display(df.head())
print("\n마지막 5개 행:")
display(df.tail())

DataFrame 구성:
(5, 4)

DataFrame 열:
Index(['이름', '점수', '나이', '성별'], dtype='object')

DataFrame 데이터 유형:
이름    object
점수     int64
나이     int64
성별    object
dtype: object

DataFrame 정보:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      5 non-null      object
 1   점수      5 non-null      int64
 2   나이      5 non-null      int64
 3   성별      5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

처음 5개 행:

  이름  점수  나이  성별
0  김  80  20  여성
1  이  92  22  여성
2  박  76  27  남성
3  최  88  39  여성
4  장  64  14  남성

마지막 5개 행:

  이름  점수  나이  성별
0  김  80  20  여성
1  이  92  22  여성
2  박  76  27  남성
3  최  88  39  여성
4  장  64  14  남성

In [26]:
print("'이름' 열을 Series로 추출:")
display(df['이름'])

print("\n'이름'과 '점수' 열을 DataFrame으로 추출:")
display(df[['이름', '점수']])

'이름' 열을 Series로 추출:

0    김
1    이
2    박
3    최
4    장
Name: 이름, dtype: object

'이름'과 '점수' 열을 DataFrame으로 추출:

  이름  점수
0  김  80
1  이  92
2  박  76
3  최  88
4  장  64

In [27]:
print("df.loc[]를 사용하여 인덱스 0인 행 추출:")
display(df.loc[0])

print("\ndf.loc[]를 사용하여 인덱스 1, 3, 4인 행 추출:")
display(df.loc[[1, 3, 4]])

df.loc[]를 사용하여 인덱스 0인 행 추출:

이름     김
점수    80
나이    20
성별    여성
Name: 0, dtype: object

df.loc[]를 사용하여 인덱스 1, 3, 4인 행 추출:

  이름  점수  나이  성별
1  이  92  22  여성
3  최  88  39  여성
4  장  64  14  남성

In [28]:
print("df.iloc[0]를 사용하여 첫 번째 행 추출:")
display(df.iloc[0])

print("\ndf.iloc[[1, 3, 4]]를 사용하여 위치 1, 3, 4에 있는 행 추출:")
display(df.iloc[[1, 3, 4]])

print("\ndf.iloc[-1]를 사용하여 마지막 행 추출:")
display(df.iloc[-1])

df.iloc[0]를 사용하여 첫 번째 행 추출:

이름     김
점수    80
나이    20
성별    여성
Name: 0, dtype: object

df.iloc[[1, 3, 4]]를 사용하여 위치 1, 3, 4에 있는 행 추출:

  이름  점수  나이  성별
1  이  92  22  여성
3  최  88  39  여성
4  장  64  14  남성

df.iloc[-1]를 사용하여 마지막 행 추출:

이름     장
점수    64
나이    14
성별    남성
Name: 4, dtype: object

In [29]:
print("df.loc[]를 사용하여 0, 1, 2 행과 '이름', '점수' 열 추출:")
display(df.loc[[0, 1, 2], ['이름', '점수']])

print("\ndf.iloc[]를 사용하여 위치 0, 1, 2 행과 위치 0, 1 열 추출:")
display(df.iloc[[0, 1, 2], [0, 1]])

df.loc[]를 사용하여 0, 1, 2 행과 '이름', '점수' 열 추출:

  이름  점수
0  김  80
1  이  92
2  박  76

df.iloc[]를 사용하여 위치 0, 1, 2 행과 위치 0, 1 열 추출:

  이름  점수
0  김  80
1  이  92
2  박  76

In [30]:
print("df.iloc[] 열 슬라이싱을 사용하여 '점수' 및 '나이' 열 추출:")
display(df.iloc[:, 1:3])

df.iloc[] 열 슬라이싱을 사용하여 '점수' 및 '나이' 열 추출:

   점수  나이
0  80  20
1  92  22
2  76  27
3  88  39
4  64  14

In [31]:
print("groupby를 사용하여 '성별' 별 '점수' 평균:")
display(df.groupby('성별')['점수'].mean())

groupby를 사용하여 '성별' 별 '점수' 평균:

성별
남성    70.000000
여성    86.666667
Name: 점수, dtype: float64

In [32]:
print("groupby와 reset_index()를 사용하여 '성별' 및 '나이' 별 '점수' 평균:")
display(df.groupby(['성별', '나이'])['점수'].mean().reset_index())

groupby와 reset_index()를 사용하여 '성별' 및 '나이' 별 '점수' 평균:

   성별  나이    점수
0  남성  14  64.0
1  남성  27  76.0
2  여성  20  80.0
3  여성  22  92.0
4  여성  39  88.0

In [33]:
print("성별별 고유한 '나이' 수 (nunique() 사용):")
display(df.groupby('성별')['나이'].nunique())

print("\n각 '성별'의 빈도수 (value_counts() 사용):")
display(df['성별'].value_counts())

성별별 고유한 '나이' 수 (nunique() 사용):

성별
남성    2
여성    3
Name: 나이, dtype: int64

각 '성별'의 빈도수 (value_counts() 사용):

성별
여성    3
남성    2
Name: count, dtype: int64