In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
gapminder = pd.read_csv("/content/drive/MyDrive/kwukdt/data-analysis/data-collection/gapminder.tsv", sep='\t')
display(gapminder)

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

          country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [12]:
# rename을 사용하여 칼럼(Column) 변경
gapminder = gapminder.rename(columns={
    'country': '국가',
    'continent': '대륙',
    'year': '연도',
    'lifeExp': '기대수명',
    'pop': '인구',
    'gdpPercap': '1인당 GDP'
})
display(gapminder.head())

            국가    대륙    연도    기대수명        인구      1인당GDP
0  Afghanistan  Asia  1952  28.801   8425333  779.445314
1  Afghanistan  Asia  1957  30.332   9240934  820.853030
2  Afghanistan  Asia  1962  31.997  10267083  853.100710
3  Afghanistan  Asia  1967  34.020  11537966  836.197138
4  Afghanistan  Asia  1972  36.088  13079460  739.981106

In [13]:
print(f"DataFrame 구성: {gapminder.shape}")
print(f"\nDataFrame 열: {gapminder.columns}")
print(f"\n===== DataFrame 데이터 유형 =====\n{gapminder.dtypes}")
print(f"\n===== DataFrame 정보 =====")
gapminder.info()
print(f"\n===== 처음 5개 행 =====")
display(gapminder.head())
print(f"\n===== 마지막 5개 행 =====")
display(gapminder.tail())

DataFrame 구성: (1704, 6)

DataFrame 열: Index(['국가', '대륙', '연도', '기대수명', '인구', '1인당GDP'], dtype='object')

===== DataFrame 데이터 유형 =====
국가         object
대륙         object
연도          int64
기대수명      float64
인구          int64
1인당GDP    float64
dtype: object

===== DataFrame 정보 =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   국가      1704 non-null   object
 1   대륙      1704 non-null   object
 2   연도      1704 non-null   int64
 3   기대수명    1704 non-null   float64
 4   인구      1704 non-null   int64
 5   1인당GDP  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

===== 처음 5개 행 =====

            국가    대륙    연도    기대수명        인구      1인당GDP
0  Afghanistan  Asia  1952  28.801   8425333  779.445314
1  Afghanistan  Asia  1957  30.332   9240934  820.853030
2  Afghanistan  Asia  1962  31.997  10267083  853.100710
3  Afghanistan  Asia  1967  34.020  11537966  836.197138
4  Afghanistan  Asia  1972  36.088  13079460  739.981106

===== 마지막 5개 행 =====

            국가      대륙    연도    기대수명        인구      1인당GDP
1699  Zimbabwe  Africa  1987  62.351   9216418  706.157306
1700  Zimbabwe  Africa  1992  60.377  10704340  693.420786
1701  Zimbabwe  Africa  1997  46.809  11404948  792.449960
1702  Zimbabwe  Africa  2002  39.989  11926563  672.038623
1703  Zimbabwe  Africa  2007  43.487  12311143  469.709298

In [19]:
# groupby를 사용하여 '국가' 별 '기대수명' 평균 (소수점 둘째자리 반올림)
display(gapminder.groupby('국가')['기대수명'].mean().round(2))

국가
Afghanistan           37.48
Albania               68.43
Algeria               59.03
Angola                37.88
Argentina             69.06
                      ...
Vietnam               57.48
West Bank and Gaza    60.33
Yemen, Rep.           46.78
Zambia                46.00
Zimbabwe              52.66
Name: 기대수명, Length: 142, dtype: float64

In [20]:
# '대륙'별 '국가'의 빈도수 (value_counts() 사용)
display(gapminder.groupby('대륙')['국가'].value_counts())

대륙       국가
Africa   Algeria           12
         Angola            12
         Benin             12
         Botswana          12
         Burkina Faso      12
                           ..
Europe   Switzerland       12
         Turkey            12
         United Kingdom    12
Oceania  Australia         12
         New Zealand       12
Name: count, Length: 142, dtype: int64