In [2]:
import pandas as pd

## 시리즈(Series) 생성

# 기본 시리즈 생성 (인덱스 자동 할당 0, 1, 2...)
s = pd.Series([42, 'banana'])
print("\n--- 기본 시리즈 생성 ---")
print(s)

# 행 이름(인덱스)을 직접 지정하여 시리즈 생성
s_indexed = pd.Series(
    [42, 'banana'],
    index=['숫자', '과일']
)
print("\n--- 인덱스 직접 지정 시리즈 생성 ---")
print(s_indexed)

--- 기본 시리즈 생성 ---
0        42
1    banana
dtype: object

--- 인덱스 직접 지정 시리즈 생성 ---
숫자        42
과일    banana
dtype: object

In [4]:
## 데이터 프레임(DataFrame) 생성 (시리즈 추출 및 활용을 위해 미리 생성)

scientists = pd.DataFrame({
    'Name': ['Rosaline Franklin', 'William Gosset', 'Marie Curie', 'Albert Einstein', 'Rachel Carson', 'Dorothy Hodgkin', 'Lise Meitner', 'Otto Hahn'],
    'Born': ['1920-07-25', '1876-06-13', '1867-11-07', '1879-03-14', '1907-05-27', '1910-05-12', '1878-11-07', '1879-03-08'],
    'Died': ['1958-04-16', '1937-10-16', '1934-07-04', '1955-04-18', '1964-04-14', '1994-07-29', '1968-10-27', '1968-07-28'],
    'Age':  [37, 61, 66, 76, 56, 84, 89, 89]
}, index=['Franklin', 'Gosset', 'Curie', 'Einstein', 'Carson', 'Hodgkin', 'Meitner', 'Hahn'])

print("\n--- scientists 데이터 프레임(DataFrame) ---")
display(scientists)

--- scientists 데이터 프레임(DataFrame) ---

                       Name        Born        Died  Age
Franklin  Rosaline Franklin  1920-07-25  1958-04-16   37
Gosset       William Gosset  1876-06-13  1937-10-16   61
Curie           Marie Curie  1867-11-07  1934-07-04   66
Einstein    Albert Einstein  1879-03-14  1955-04-18   76
Carson        Rachel Carson  1907-05-27  1964-04-14   56
Hodgkin     Dorothy Hodgkin  1910-05-12  1994-07-29   84
Meitner        Lise Meitner  1878-11-07  1968-10-27   89
Hahn              Otto Hahn  1879-03-08  1968-07-28   89

In [7]:
## 시리즈(Series) 추출

# DataFrame에서 'Age' 열 추출 (시리즈 반환)
ages = scientists['Age']
print("\n--- 'Age' 열 (Series) 추출 ---")
print(ages)
print(f"'Age' 열의 타입: {type(ages)}")

# DataFrame에서 특정 행 추출 → Series 반환
first_row = scientists.loc['Gosset']
print("\n--- 'Gosset' 행 (Series) 추출 ---")
print(first_row)
print(f"'Gosset' 행의 타입: {type(first_row)}")


# 시리즈(Series)의 주요 속성(Attribute)과 메서드(Method)
print("\n--- 시리즈 속성 및 메서드 ---")
print(f"인덱스: {ages.index}")
print(f"값 배열 (numpy ndarray): {ages.values}")
print(f"자료형: {ages.dtype}")
print(f"형태 (shape): {ages.shape}")
print(f"전체 요소 수 (size): {ages.size}")
print(f"인덱스 키: {ages.keys()}")
print(f"첫 번째 인덱스 키: {ages.keys()[0]}")
print(f"첫 번째 인덱스: {ages.index[0]}")

--- 'Age' 열 (Series) 추출 ---
Franklin    37
Gosset      61
Curie       66
Einstein    76
Carson      56
Hodgkin     84
Meitner     89
Hahn        89
Name: Age, dtype: int64
'Age' 열의 타입: <class 'pandas.core.series.Series'>

--- 'Gosset' 행 (Series) 추출 ---
Name    William Gosset
Born        1876-06-13
Died        1937-10-16
Age                 61
Name: Gosset, dtype: object
'Gosset' 행의 타입: <class 'pandas.core.series.Series'>

--- 시리즈 속성 및 메서드 ---
인덱스: Index(['Franklin', 'Gosset', 'Curie', 'Einstein', 'Carson', 'Hodgkin',
       'Meitner', 'Hahn'],
      dtype='object')
값 배열 (numpy ndarray): [37 61 66 76 56 84 89 89]
자료형: int64
형태 (shape): (8,)
전체 요소 수 (size): 8
인덱스 키: Index(['Franklin', 'Gosset', 'Curie', 'Einstein', 'Carson', 'Hodgkin',
       'Meitner', 'Hahn'],
      dtype='object')
첫 번째 인덱스 키: Franklin
첫 번째 인덱스: Franklin

In [8]:
## 시리즈(Series) 메서드(Method)

print("\n--- 시리즈 통계 메서드 ---")
print(f"평균 나이: {ages.mean()}")
print(f"최솟값 나이: {ages.min()}")
print(f"최댓값 나이: {ages.max()}")
print(f"표준편차 나이: {ages.std()}")
print("기술통계 요약:")
print(ages.describe())

# 값 기준 정렬 (오름차순이 기본)
print("\n--- 나이 값 기준 정렬 ---")
print(ages.sort_values(ascending=True))

# 인덱스 기준 정렬 (내림차순)
print("\n--- 인덱스 기준 정렬 ---")
print(ages.sort_index(ascending=False))

# 무작위 샘플링 (전체 100% 추출)
print("\n--- 무작위 샘플링 (frac=1) ---")
print(ages.sample(frac=1, random_state=42))

--- 시리즈 통계 메서드 ---
평균 나이: 69.75
최솟값 나이: 37
최댓값 나이: 89
표준편차 나이: 18.26589327525093
기술통계 요약:
count     8.000000
mean     69.750000
std      18.265893
min      37.000000
25%      59.750000
50%      71.000000
75%      85.250000
max      89.000000
Name: Age, dtype: float64

--- 나이 값 기준 정렬 ---
Franklin    37
Carson      56
Gosset      61
Curie       66
Einstein    76
Hodgkin     84
Meitner     89
Hahn        89
Name: Age, dtype: int64

--- 인덱스 기준 정렬 ---
Meitner     89
Hodgkin     84
Hahn        89
Gosset      61
Franklin    37
Einstein    76
Curie       66
Carson      56
Name: Age, dtype: int64

--- 무작위 샘플링 (frac=1) ---
Gosset      61
Hodgkin     84
Franklin    37
Hahn        89
Curie       66
Carson      56
Einstein    76
Meitner     89
Name: Age, dtype: int64

In [11]:
## 불리언 시리즈(Boolean Series)

print("\n--- 평균 나이보다 많은 과학자만 추출 (불리언 시리즈) ---")
# 평균 나이보다 많은 과학자만 추출
ages_greater_than_mean = ages[ages > ages.mean()]
print(ages_greater_than_mean)

print("\n--- 불리언 시리즈 직접 지정하여 추출 ---")
# True/False 리스트를 직접 지정
bool_mask = pd.Series([True, False, True, False, True, False, True, False], index=ages.index)
print(ages[bool_mask])

--- 평균 나이보다 많은 과학자만 추출 (불리언 시리즈) ---
Einstein    76
Hodgkin     84
Meitner     89
Hahn        89
Name: Age, dtype: int64

--- 불리언 시리즈 직접 지정하여 추출 ---
Franklin    37
Curie       66
Carson      56
Meitner     89
Name: Age, dtype: int64

In [12]:
## 벡터화 연산(Vectorized Operations)

print("\n--- 벡터와 벡터 연산 (길이 같음) ---")
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([10, 20, 30])
print(f"s1: {s1}\ns2: {s2}")
print(f"s1 + s2:\n{s1 + s2}")

print("\n--- 벡터와 벡터 연산 (길이 다름) ---")
s1_long = pd.Series([1, 2, 3, 4, 5, 6, 7, 8])  # 길이 8
s2_short = pd.Series([10, 20])                   # 길이 2
print(f"s1_long: {s1_long}\ns2_short: {s2_short}")
# 인덱스가 없는 부분은 NaN (Not a Number)으로 처리됨
print(f"s1_long + s2_short:\n{s1_long + s2_short}")

print("\n--- 벡터와 스칼라 연산 ---")
# 'Age' 시리즈의 모든 나이를 2배
print(f"Age * 2:\n{ages * 2}")
# 'Age' 시리즈의 모든 나이에 100 더하기
print(f"Age + 100:\n{ages + 100}")

# 문자열 열에 스칼라 연산 (반복)
name_series = scientists['Name']
print(f"\nName * 2:\n{name_series * 2}")

--- 벡터와 벡터 연산 (길이 같음) ---
s1: 0    1
1    2
2    3
dtype: int64
s2: 0    10
1    20
2    30
dtype: int64
s1 + s2:
0    11
1    22
2    33
dtype: int64

--- 벡터와 벡터 연산 (길이 다름) ---
s1_long: 0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64
s2_short: 0    10
1    20
dtype: int64
s1_long + s2_short:
0    11.0
1    22.0
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
dtype: float64

--- 벡터와 스칼라 연산 ---
Age * 2:
Franklin     74
Gosset      122
Curie       132
Einstein    152
Carson      112
Hodgkin     168
Meitner     178
Hahn        178
Name: Age, dtype: int64
Age + 100:
Franklin    137
Gosset      161
Curie       166
Einstein    176
Carson      156
Hodgkin     184
Meitner     189
Hahn        189
Name: Age, dtype: int64

Name * 2:
Franklin    Rosaline FranklinRosaline Franklin
Gosset            William GossetWilliam Gosset
Curie                   Marie CurieMarie Curie
Einstein        Albert EinsteinAlbert Einstein
Carson              Rachel CarsonRachel Carson
Hodgkin         Dorothy HodgkinDorothy Hodgkin
Meitner               Lise MeitnerLise Meitner
Hahn                        Otto HahnOtto Hahn
Name: Name, dtype: object

In [15]:
## 자동 정렬 (인덱스 기준)

print("--- 시리즈 자동 정렬 ---")
# ages: 오름차순 인덱스 (기본)
print(f"ages:\n{ages}")

# rev_ages: 인덱스를 내림차순으로 정렬
rev_ages = ages.sort_index(ascending=False)
print(f"\nrev_ages (인덱스 내림차순):\n{rev_ages}")

# ages와 rev_ages를 더하면, 인덱스 기준으로 같은 인덱스끼리 찾아서 더하고,
# 결과는 오름차순 인덱스로 자동 정렬됨
print(f"\nages + rev_ages (자동 정렬 결과):\n{ages + rev_ages}")

--- 시리즈 자동 정렬 ---
ages:
Franklin    37
Gosset      61
Curie       66
Einstein    76
Carson      56
Hodgkin     84
Meitner     89
Hahn        89
Name: Age, dtype: int64

rev_ages (인덱스 내림차순):
Meitner     89
Hodgkin     84
Hahn        89
Gosset      61
Franklin    37
Einstein    76
Curie       66
Carson      56
Name: Age, dtype: int64

ages + rev_ages (자동 정렬 결과):
Carson      112
Curie       132
Einstein    152
Franklin     74
Gosset      122
Hahn        178
Hodgkin     168
Meitner     178
Name: Age, dtype: int64

In [19]:
## 데이터 프레임(DataFrame) 생성

print("--- 딕셔너리로 DataFrame 생성 ---")
# 딕셔너리를 사용하여 DataFrame 생성
df_from_dict = pd.DataFrame({
    'Name': ['Rosaline Franklin', 'William Gosset'],
    'Born': ['1920-07-25', '1876-06-13'],
    'Died': ['1958-04-16', '1937-10-16'],
    'Age':  [37, 61]
})
display(df_from_dict)

print("\n--- 딕셔너리로 DataFrame 생성 (열 순서 및 행 이름 지정) ---")
# 열 순서와 행 이름을 직접 지정하여 DataFrame 생성
df_custom = pd.DataFrame(
    data={
        'Name': ['Rosaline Franklin', 'William Gosset'],
        'Born': ['1920-07-25', '1876-06-13'],
        'Died': ['1958-04-16', '1937-10-16'],
        'Age':  [37, 61]
    },
    columns=['Name', 'Born', 'Died', 'Age'],  # 열 순서 지정
    index=['Franklin', 'Gosset']              # 행 이름 지정
)
display(df_custom)

--- 딕셔너리로 DataFrame 생성 ---

                Name        Born        Died  Age
0  Rosaline Franklin  1920-07-25  1958-04-16   37
1     William Gosset  1876-06-13  1937-10-16   61

--- 딕셔너리로 DataFrame 생성 (열 순서 및 행 이름 지정) ---

                       Name        Born        Died  Age
Franklin  Rosaline Franklin  1920-07-25  1958-04-16   37
Gosset       William Gosset  1876-06-13  1937-10-16   61

In [18]:
## 데이터 프레임(DataFrame) 구성 요소

print("--- DataFrame 구성 요소 ---")
print(f"\n행 이름 (인덱스): {scientists.index}")
print(f"\n열 이름 (컬럼): {scientists.columns}")
print(f"\n실제 데이터 (numpy 배열):\n{scientists.values}")

--- DataFrame 구성 요소 ---

행 이름 (인덱스): Index(['Franklin', 'Gosset', 'Curie', 'Einstein', 'Carson', 'Hodgkin',
       'Meitner', 'Hahn'],
      dtype='object')

열 이름 (컬럼): Index(['Name', 'Born', 'Died', 'Age'], dtype='object')

실제 데이터 (numpy 배열):
[['Rosaline Franklin' '1920-07-25' '1958-04-16' 37]
 ['William Gosset' '1876-06-13' '1937-10-16' 61]
 ['Marie Curie' '1867-11-07' '1934-07-04' 66]
 ['Albert Einstein' '1879-03-14' '1955-04-18' 76]
 ['Rachel Carson' '1907-05-27' '1964-04-14' 56]
 ['Dorothy Hodgkin' '1910-05-12' '1994-07-29' 84]
 ['Lise Meitner' '1878-11-07' '1968-10-27' 89]
 ['Otto Hahn' '1879-03-08' '1968-07-28' 89]]

In [20]:
## 불리언 데이터 프레임(Boolean DataFrame)

print("--- 'Age' 열의 평균보다 큰 행만 추출 (불리언 DataFrame) ---")
# 'Age' 열의 평균보다 나이가 많은 과학자만 포함하는 행 추출
display(scientists[scientists['Age'] > scientists['Age'].mean()])

print("\n--- 열 이름 문자열로 Series 추출 ---")
# 'Name' 열을 Series로 추출
display(scientists['Name'])

print("\n--- 열 이름 리스트로 DataFrame 추출 ---")
# 'Name'과 'Age' 열을 DataFrame으로 추출
display(scientists[['Name', 'Age']])

print("\n--- loc로 특정 행/열 추출 ---")
# 'Franklin' 행의 모든 열 추출 (Series)
display(scientists.loc['Franklin'])
# 'Franklin' 행의 'Name'과 'Age' 열 추출 (Series)
display(scientists.loc['Franklin', ['Name', 'Age']])

print("\n--- iloc로 특정 행/열 추출 (숫자 인덱스) ---")
# 첫 번째 행 (인덱스 0)의 모든 열 추출 (Series)
display(scientists.iloc[0])
# 첫 번째 행 (인덱스 0)의 첫 번째, 네 번째 열 추출 (Series)
display(scientists.iloc[0, [0, 3]])

--- 'Age' 열의 평균보다 큰 행만 추출 (불리언 DataFrame) ---

                     Name        Born        Died  Age
Einstein  Albert Einstein  1879-03-14  1955-04-18   76
Hodgkin   Dorothy Hodgkin  1910-05-12  1994-07-29   84
Meitner      Lise Meitner  1878-11-07  1968-10-27   89
Hahn            Otto Hahn  1879-03-08  1968-07-28   89

--- 열 이름 문자열로 Series 추출 ---

Franklin    Rosaline Franklin
Gosset         William Gosset
Curie             Marie Curie
Einstein      Albert Einstein
Carson          Rachel Carson
Hodgkin       Dorothy Hodgkin
Meitner          Lise Meitner
Hahn                Otto Hahn
Name: Name, dtype: object

--- 열 이름 리스트로 DataFrame 추출 ---

                       Name  Age
Franklin  Rosaline Franklin   37
Gosset       William Gosset   61
Curie           Marie Curie   66
Einstein    Albert Einstein   76
Carson        Rachel Carson   56
Hodgkin     Dorothy Hodgkin   84
Meitner        Lise Meitner   89
Hahn              Otto Hahn   89

--- loc로 특정 행/열 추출 ---

Name    Rosaline Franklin
Born           1920-07-25
Died           1958-04-16
Age                    37
Name: Franklin, dtype: object

Name    Rosaline Franklin
Age                    37
Name: Franklin, dtype: object

--- iloc로 특정 행/열 추출 (숫자 인덱스) ---

Name    Rosaline Franklin
Born           1920-07-25
Died           1958-04-16
Age                    37
Name: Franklin, dtype: object

Name    Rosaline Franklin
Age                    37
Name: Franklin, dtype: object

In [22]:
## 브로드캐스팅(Broadcasting)

print("--- DataFrame 간 연산 (add() 메서드) ---")
first_half  = scientists.iloc[:4]   # 앞 절반
second_half = scientists.iloc[4:]   # 뒤 절반

print("\n첫 절반 DataFrame:")
display(first_half)
print("\n뒤 절반 DataFrame:")
display(second_half)

# DataFrame 간 덧셈 (인덱스와 컬럼이 일치하는 셀끼리 연산, 없으면 NaN)
print("\nfirst_half + second_half (add() 메서드):")
display(first_half.add(second_half))

print("\n--- DataFrame과 스칼라 연산 ---")
# 숫자 열은 값 * 2, 문자열 열은 문자열 2번 반복
print("\nscientists * 2:")
display(scientists * 2)

--- DataFrame 간 연산 (add() 메서드) ---

첫 절반 DataFrame:

                       Name        Born        Died  Age
Franklin  Rosaline Franklin  1920-07-25  1958-04-16   37
Gosset       William Gosset  1876-06-13  1937-10-16   61
Curie           Marie Curie  1867-11-07  1934-07-04   66
Einstein    Albert Einstein  1879-03-14  1955-04-18   76

뒤 절반 DataFrame:

                    Name        Born        Died  Age
Carson     Rachel Carson  1907-05-27  1964-04-14   56
Hodgkin  Dorothy Hodgkin  1910-05-12  1994-07-29   84
Meitner     Lise Meitner  1878-11-07  1968-10-27   89
Hahn           Otto Hahn  1879-03-08  1968-07-28   89

first_half + second_half (add() 메서드):

         Name Born Died  Age
Carson    NaN  NaN  NaN  NaN
Curie     NaN  NaN  NaN  NaN
Einstein  NaN  NaN  NaN  NaN
Franklin  NaN  NaN  NaN  NaN
Gosset    NaN  NaN  NaN  NaN
Hahn      NaN  NaN  NaN  NaN
Hodgkin   NaN  NaN  NaN  NaN
Meitner   NaN  NaN  NaN  NaN

--- DataFrame과 스칼라 연산 ---

scientists * 2:

,Name,Born,Died,Age
Franklin,Rosaline FranklinRosaline Franklin,1920-07-251920-07-25,1958-04-161958-04-16,74
Gosset,William GossetWilliam Gosset,1876-06-131876-06-13,1937-10-161937-10-16,122
Curie,Marie CurieMarie Curie,1867-11-071867-11-07,1934-07-041934-07-04,132
Einstein,Albert EinsteinAlbert Einstein,1879-03-141879-03-14,1955-04-181955-04-18,152
Carson,Rachel CarsonRachel Carson,1907-05-271907-05-27,1964-04-141964-04-14,112
Hodgkin,Dorothy HodgkinDorothy Hodgkin,1910-05-121910-05-12,1994-07-291994-07-29,168
Meitner,Lise MeitnerLise Meitner,1878-11-071878-11-07,1968-10-271968-10-27,178
Hahn,Otto HahnOtto Hahn,1879-03-081879-03-08,1968-07-281968-07-28,178

In [25]:
## 데이터 변환

print("--- Datetime형 변환 및 열 추가 (직접 할당) ---")
# 'Born'과 'Died' 열을 Datetime형으로 변환
born_datetime = pd.to_datetime(scientists['Born'], format='%Y-%m-%d')
died_datetime = pd.to_datetime(scientists['Died'], format='%Y-%m-%d')

# 새로운 열 'born_dt'와 'died_dt' 추가
scientists['born_dt'] = born_datetime
scientists['died_dt'] = died_datetime

# 날짜 차이 계산 및 'age_days' 열 추가 (Timedelta 형태)
scientists['age_days'] = scientists['died_dt'] - scientists['born_dt']

# 날짜 차이를 일수로 변환하여 'age_years' 열 추가
scientists['age_years'] = scientists['age_days'].dt.days / 365

print("\ndatetime 변환 및 age_days, age_years 열 추가 후 DataFrame:")
display(scientists.head())

print("\n--- assign() 메서드를 이용한 열 추가 (메서드 체이닝) ---")
# assign()을 사용하여 새로운 DataFrame을 반환받음
scientists_assigned = scientists.assign(
    age_days_assign  = lambda x: x['died_dt'] - x['born_dt'],
    age_years_assign = lambda x: x['age_days_assign'].dt.days / 365
)

print("\nassign()을 사용하여 age_days_assign, age_years_assign 열 추가 후 DataFrame:")
display(scientists_assigned.head())

--- Datetime형 변환 및 열 추가 (직접 할당) ---

datetime 변환 및 age_days, age_years 열 추가 후 DataFrame:

,Name,Born,Died,Age,born_dt,died_dt,age_days,age_years
Franklin,Rosaline Franklin,1920-07-25,1958-04-16,37,1920-07-25,1958-04-16,13779 days,37.750685
Gosset,William Gosset,1876-06-13,1937-10-16,61,1876-06-13,1937-10-16,22404 days,61.380822
Curie,Marie Curie,1867-11-07,1934-07-04,66,1867-11-07,1934-07-04,24345 days,66.698630
Einstein,Albert Einstein,1879-03-14,1955-04-18,76,1879-03-14,1955-04-18,27793 days,76.145205
Carson,Rachel Carson,1907-05-27,1964-04-14,56,1907-05-27,1964-04-14,20777 days,56.923288

--- assign() 메서드를 이용한 열 추가 (메서드 체이닝) ---

assign()을 사용하여 age_days_assign, age_years_assign 열 추가 후 DataFrame:

,Name,Born,Died,Age,born_dt,died_dt,age_days,age_years,age_days_assign,age_years_assign
Franklin,Rosaline Franklin,1920-07-25,1958-04-16,37,1920-07-25,1958-04-16,13779 days,37.750685,13779 days,37.750685
Gosset,William Gosset,1876-06-13,1937-10-16,61,1876-06-13,1937-10-16,22404 days,61.380822,22404 days,61.380822
Curie,Marie Curie,1867-11-07,1934-07-04,66,1867-11-07,1934-07-04,24345 days,66.698630,24345 days,66.698630
Einstein,Albert Einstein,1879-03-14,1955-04-18,76,1879-03-14,1955-04-18,27793 days,76.145205,27793 days,76.145205
Carson,Rachel Carson,1907-05-27,1964-04-14,56,1907-05-27,1964-04-14,20777 days,56.923288,20777 days,56.923288

In [29]:
## 열 내용 변환

print("--- sample()로 시리즈 값 무작위 추출 및 할당 ---")
# 'Age' 열을 무작위로 섞음 (frac=1은 전체를 의미, random_state로 재현 가능)
shuffled_ages = scientists['Age'].sample(frac=1, random_state=42)
print("\n무작위로 섞인 'Age' 시리즈:\n", shuffled_ages)

# 잘못된 방법: 인덱스 기준으로 자동 병합되어 원래 순서로 돌아감
scientists_wrong_assign = scientists.copy()
scientists_wrong_assign['Age'] = shuffled_ages
print("\n잘못된 할당 (인덱스 자동 병합으로 인해 원본 순서 유지):\n")
display(scientists_wrong_assign)

# 올바른 방법: .values로 인덱스를 제거하고 값만 할당
scientists_correct_assign = scientists.copy()
scientists_correct_assign['Age'] = shuffled_ages.values
print("\n올바른 할당 (인덱스 제거 후 값 할당):\n")
display(scientists_correct_assign)

--- sample()로 시리즈 값 무작위 추출 및 할당 ---

무작위로 섞인 'Age' 시리즈:
 Gosset      61
Hodgkin     84
Franklin    37
Hahn        89
Curie       66
Carson      56
Einstein    76
Meitner     89
Name: Age, dtype: int64

잘못된 할당 (인덱스 자동 병합으로 인해 원본 순서 유지):

,Name,Born,Died,Age,born_dt,died_dt,age_days,age_years
Franklin,Rosaline Franklin,1920-07-25,1958-04-16,37,1920-07-25,1958-04-16,13779 days,37.750685
Gosset,William Gosset,1876-06-13,1937-10-16,61,1876-06-13,1937-10-16,22404 days,61.380822
Curie,Marie Curie,1867-11-07,1934-07-04,66,1867-11-07,1934-07-04,24345 days,66.698630
Einstein,Albert Einstein,1879-03-14,1955-04-18,76,1879-03-14,1955-04-18,27793 days,76.145205
Carson,Rachel Carson,1907-05-27,1964-04-14,56,1907-05-27,1964-04-14,20777 days,56.923288
Hodgkin,Dorothy Hodgkin,1910-05-12,1994-07-29,84,1910-05-12,1994-07-29,30759 days,84.271233
Meitner,Lise Meitner,1878-11-07,1968-10-27,89,1878-11-07,1968-10-27,32861 days,90.030137
Hahn,Otto Hahn,1879-03-08,1968-07-28,89,1879-03-08,1968-07-28,32649 days,89.449315

올바른 할당 (인덱스 제거 후 값 할당):

,Name,Born,Died,Age,born_dt,died_dt,age_days,age_years
Franklin,Rosaline Franklin,1920-07-25,1958-04-16,61,1920-07-25,1958-04-16,13779 days,37.750685
Gosset,William Gosset,1876-06-13,1937-10-16,84,1876-06-13,1937-10-16,22404 days,61.380822
Curie,Marie Curie,1867-11-07,1934-07-04,37,1867-11-07,1934-07-04,24345 days,66.698630
Einstein,Albert Einstein,1879-03-14,1955-04-18,89,1879-03-14,1955-04-18,27793 days,76.145205
Carson,Rachel Carson,1907-05-27,1964-04-14,66,1907-05-27,1964-04-14,20777 days,56.923288
Hodgkin,Dorothy Hodgkin,1910-05-12,1994-07-29,56,1910-05-12,1994-07-29,30759 days,84.271233
Meitner,Lise Meitner,1878-11-07,1968-10-27,76,1878-11-07,1968-10-27,32861 days,90.030137
Hahn,Otto Hahn,1879-03-08,1968-07-28,89,1879-03-08,1968-07-28,32649 days,89.449315

In [26]:
## 날짜 차이로 나이 계산하기 (.dt 접근자)

# 'age_days'는 이미 Timedelta 형태로 저장되어 있음
print("--- 날짜 차이 (Timedelta) ---")
print(scientists['age_days'].head())

# .dt 접근자를 사용하여 날짜 정보 추출
print("\n--- .dt.days (총 일수) ---")
print(scientists['age_days'].dt.days.head())
print("\n--- .dt.year (연도) ---")
print(scientists['born_dt'].dt.year.head())
print("\n--- .dt.month (월) ---")
print(scientists['died_dt'].dt.month.head())

--- 날짜 차이 (Timedelta) ---
Franklin   13779 days
Gosset     22404 days
Curie      24345 days
Einstein   27793 days
Carson     20777 days
Name: age_days, dtype: timedelta64[ns]

--- .dt.days (총 일수) ---
Franklin    13779
Gosset      22404
Curie       24345
Einstein    27793
Carson      20777
Name: age_days, dtype: int64

--- .dt.year (연도) ---
Franklin    1920
Gosset      1876
Curie       1867
Einstein    1879
Carson      1907
Name: born_dt, dtype: int32

--- .dt.month (월) ---
Franklin     4
Gosset      10
Curie        7
Einstein     4
Carson       4
Name: died_dt, dtype: int32

In [27]:
## 열 삭제하기

print("--- 단일 열 삭제 (drop() 메서드) ---")
# 'Age' 열 삭제 (원본 수정 안함, 새로운 DataFrame 반환)
scientists_dropped_age = scientists.drop('Age', axis=1)
print("'Age' 열 삭제 후 DataFrame:")
display(scientists_dropped_age.head())

print("\n--- 여러 열 삭제 (drop() 메서드) ---")
# 'Born', 'Died' 열 삭제
scientists_dropped_multiple = scientists.drop(['Born', 'Died'], axis=1)
print("'Born', 'Died' 열 삭제 후 DataFrame:")
display(scientists_dropped_multiple.head())

print("\n--- 필요한 열만 남기는 방법 ---")
# 'Name'과 'Age' 열만 선택
scientists_selected = scientists[['Name', 'Age']]
print("'Name', 'Age' 열만 선택한 DataFrame:")
display(scientists_selected.head())

--- 단일 열 삭제 (drop() 메서드) ---
'Age' 열 삭제 후 DataFrame:

,Name,Born,Died,born_dt,died_dt,age_days,age_years
Franklin,Rosaline Franklin,1920-07-25,1958-04-16,1920-07-25,1958-04-16,13779 days,37.750685
Gosset,William Gosset,1876-06-13,1937-10-16,1876-06-13,1937-10-16,22404 days,61.380822
Curie,Marie Curie,1867-11-07,1934-07-04,1867-11-07,1934-07-04,24345 days,66.698630
Einstein,Albert Einstein,1879-03-14,1955-04-18,1879-03-14,1955-04-18,27793 days,76.145205
Carson,Rachel Carson,1907-05-27,1964-04-14,1907-05-27,1964-04-14,20777 days,56.923288

--- 여러 열 삭제 (drop() 메서드) ---
'Born', 'Died' 열 삭제 후 DataFrame:

                       Name  Age    born_dt    died_dt   age_days  age_years
Franklin  Rosaline Franklin   37 1920-07-25 1958-04-16 13779 days  37.750685
Gosset       William Gosset   61 1876-06-13 1937-10-16 22404 days  61.380822
Curie           Marie Curie   66 1867-11-07 1934-07-04 24345 days  66.698630
Einstein    Albert Einstein   76 1879-03-14 1955-04-18 27793 days  76.145205
Carson        Rachel Carson   56 1907-05-27 1964-04-14 20777 days  56.923288

--- 필요한 열만 남기는 방법 ---
'Name', 'Age' 열만 선택한 DataFrame:

                       Name  Age
Franklin  Rosaline Franklin   37
Gosset       William Gosset   61
Curie           Marie Curie   66
Einstein    Albert Einstein   76
Carson        Rachel Carson   56