In [26]:
import pandas as pd
import os

# 'output' 디렉토리 연결
output_dir = '/content/drive/MyDrive/kwukdt/data-analysis/pandas-example/output'
os.makedirs(output_dir, exist_ok=True)

In [27]:
scientists = pd.read_csv("/content/drive/MyDrive/kwukdt/data-analysis/data-collection/scientists.csv")
display(scientists)

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [28]:
# 피클(Pickle)
# scientists 데이터프레임에서 Name 열 추출
scientists_names = scientists['Name']

# 시리즈(Series)를 피클로 저장
series_pickle_path = os.path.join(output_dir, 'scientists_names.pkl')
scientists_names.to_pickle(series_pickle_path)
print(f"시리즈를 '{series_pickle_path}'에 저장했습니다.")

# 데이터프레임(DataFrame)을 피클로 저장
df_pickle_path = os.path.join(output_dir, 'scientists_df.pkl')
scientists.to_pickle(df_pickle_path)
print(f"데이터프레임을 '{df_pickle_path}'에 저장했습니다.")

시리즈를 '/content/drive/MyDrive/kwukdt/data-analysis/pandas-example/output/scientists_names.pkl'에 저장했습니다.
데이터프레임을 '/content/drive/MyDrive/kwukdt/data-analysis/pandas-example/output/scientists_df.pkl'에 저장했습니다.

In [41]:
# 시리즈 피클 불러오기
loaded_names = pd.read_pickle(series_pickle_path)
print("불러온 시리즈 (처음 5개):")
display(loaded_names.head())

# 데이터프레임 피클 불러오기
loaded_scientists = pd.read_pickle(df_pickle_path)
print("\n불러온 데이터프레임 (처음 5개):")
display(loaded_scientists.head())

불러온 시리즈 (처음 5개):

0       Rosaline Franklin
1          William Gosset
2    Florence Nightingale
3             Marie Curie
4           Rachel Carson
Name: Name, dtype: object

불러온 데이터프레임 (처음 5개):

                   Name        Born        Died  Age    Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1        William Gosset  1876-06-13  1937-10-16   61  Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90         Nurse
3           Marie Curie  1867-11-07  1934-07-04   66       Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56     Biologist

In [30]:
# CSV/TSV 파일
# 데이터프레임을 CSV로 저장 (인덱스 제외)
csv_path = os.path.join(output_dir, 'scientists.csv')
scientists.to_csv(csv_path, index=False)
print(f"데이터프레임을 '{csv_path}'에 CSV 형식으로 저장했습니다.")

# 데이터프레임을 TSV로 저장 (탭 구분자, 인덱스 제외)
tsv_path = os.path.join(output_dir, 'scientists.tsv')
scientists.to_csv(tsv_path, sep='\t', index=False)
print(f"데이터프레임을 '{tsv_path}'에 TSV 형식으로 저장했습니다.")

데이터프레임을 '/content/drive/MyDrive/kwukdt/data-analysis/pandas-example/output/scientists.csv'에 CSV 형식으로 저장했습니다.
데이터프레임을 '/content/drive/MyDrive/kwukdt/data-analysis/pandas-example/output/scientists.tsv'에 TSV 형식으로 저장했습니다.

In [40]:
# CSV 파일 불러오기
loaded_scientists_csv = pd.read_csv(csv_path)
print("불러온 CSV 데이터프레임 (처음 5개):")
display(loaded_scientists_csv.head())

# TSV 파일 불러오기 (탭 구분자 지정)
loaded_scientists_tsv = pd.read_csv(tsv_path, sep='\t')
print("\n불러온 TSV 데이터프레임 (처음 5개):")
display(loaded_scientists_tsv.head())

불러온 CSV 데이터프레임 (처음 5개):

                   Name        Born        Died  Age    Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1        William Gosset  1876-06-13  1937-10-16   61  Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90         Nurse
3           Marie Curie  1867-11-07  1934-07-04   66       Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56     Biologist

불러온 TSV 데이터프레임 (처음 5개):

                   Name        Born        Died  Age    Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1        William Gosset  1876-06-13  1937-10-16   61  Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90         Nurse
3           Marie Curie  1867-11-07  1934-07-04   66       Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56     Biologist

In [32]:
# 엑셀(Excel)
# openpyxl 라이브러리 설치
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [33]:
# 시리즈(Series)를 DataFrame으로 변환
scientists_names_df = scientists['Name'].to_frame(name='Name')

# 변환된 시리즈 DataFrame을 엑셀로 저장 (인덱스 제외)
series_excel_path = os.path.join(output_dir, 'scientists_names.xlsx')
scientists_names_df.to_excel(series_excel_path, index=False)
print(f"시리즈 데이터프레임을 '{series_excel_path}'에 저장했습니다.")

# 데이터프레임(DataFrame)을 엑셀로 저장 (인덱스 제외)
df_excel_path = os.path.join(output_dir, 'scientists_df.xlsx')
scientists.to_excel(df_excel_path, index=False)
print(f"데이터프레임을 '{df_excel_path}'에 저장했습니다.")

시리즈 데이터프레임을 '/content/drive/MyDrive/kwukdt/data-analysis/pandas-example/output/scientists_names.xlsx'에 저장했습니다.
데이터프레임을 '/content/drive/MyDrive/kwukdt/data-analysis/pandas-example/output/scientists_df.xlsx'에 저장했습니다.

In [39]:
# 시리즈 엑셀 파일 불러오기
loaded_names_excel = pd.read_excel(series_excel_path)
print("불러온 시리즈 엑셀 데이터프레임 (처음 5개):")
display(loaded_names_excel.head())

# 데이터프레임 엑셀 파일 불러오기
loaded_scientists_excel = pd.read_excel(df_excel_path)
print("\n불러온 엑셀 데이터프레임 (처음 5개):")
display(loaded_scientists_excel.head())

불러온 시리즈 엑셀 데이터프레임 (처음 5개):

                   Name
0     Rosaline Franklin
1        William Gosset
2  Florence Nightingale
3           Marie Curie
4         Rachel Carson

불러온 엑셀 데이터프레임 (처음 5개):

                   Name        Born        Died  Age    Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1        William Gosset  1876-06-13  1937-10-16   61  Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90         Nurse
3           Marie Curie  1867-11-07  1934-07-04   66       Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56     Biologist

In [35]:
# Feather
# pyarrow 라이브러리 설치
!pip install pyarrow

Requirement already satisfied: pyarrow in /usr/local/lib/python3.12/dist-packages (18.1.0)

In [36]:
# 데이터프레임을 Feather 파일로 저장
feather_path = os.path.join(output_dir, 'scientists.feather')
scientists.to_feather(feather_path)
print(f"데이터프레임을 '{feather_path}'에 Feather 형식으로 저장했습니다.")

데이터프레임을 '/content/drive/MyDrive/kwukdt/data-analysis/pandas-example/output/scientists.feather'에 Feather 형식으로 저장했습니다.

In [38]:
# Feather 파일 불러오기
loaded_scientists_feather = pd.read_feather(feather_path)
print("불러온 Feather 데이터프레임 (처음 5개):")
display(loaded_scientists_feather.head())

불러온 Feather 데이터프레임 (처음 5개):

                   Name        Born        Died  Age    Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1        William Gosset  1876-06-13  1937-10-16   61  Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90         Nurse
3           Marie Curie  1867-11-07  1934-07-04   66       Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56     Biologist

In [42]:
# 딕셔너리(Dictionary)
from pprint import pprint

# DataFrame을 'index' orient로 딕셔너리로 변환
# 현재 scientists 데이터프레임의 'Born'과 'Died'는 문자열
scientists_dict = scientists.to_dict(orient='index')
print("DataFrame을 딕셔너리로 변환 (처음 2개 항목):")
for i, (idx, row_dict) in enumerate(scientists_dict.items()):
    if i >= 2:
        break
    pprint(f"인덱스 {idx}: {row_dict}")

DataFrame을 딕셔너리로 변환 (처음 2개 항목):
("인덱스 0: {'Name': 'Rosaline Franklin', 'Born': '1920-07-25', 'Died': "
 "'1958-04-16', 'Age': 37, 'Occupation': 'Chemist'}")
("인덱스 1: {'Name': 'William Gosset', 'Born': '1876-06-13', 'Died': "
 "'1937-10-16', 'Age': 61, 'Occupation': 'Statistician'}")

In [44]:
# 딕셔너리를 다시 DataFrame으로 변환
loaded_scientists_dict = pd.DataFrame.from_dict(scientists_dict, orient='index')

# 'Born'과 'Died' 열이 문자열로 로드되었을 수 있으므로 datetime 객체로 다시 변환
loaded_scientists_dict['Born'] = pd.to_datetime(loaded_scientists_dict['Born'])
loaded_scientists_dict['Died'] = pd.to_datetime(loaded_scientists_dict['Died'])

print("딕셔너리에서 불러온 데이터프레임 (처음 5개):")
display(loaded_scientists_dict.head())

딕셔너리에서 불러온 데이터프레임 (처음 5개):

                   Name       Born       Died  Age    Occupation
0     Rosaline Franklin 1920-07-25 1958-04-16   37       Chemist
1        William Gosset 1876-06-13 1937-10-16   61  Statistician
2  Florence Nightingale 1820-05-12 1910-08-13   90         Nurse
3           Marie Curie 1867-11-07 1934-07-04   66       Chemist
4         Rachel Carson 1907-05-27 1964-04-14   56     Biologist

In [46]:
# JSON(JavaScript Object Notation)
import io

# 데이터프레임을 JSON 문자열로 변환 (각 행을 딕셔너리로 표현, 2칸 들여쓰기)
# scientists 데이터프레임에는 'DiscoverDate' 열이 없으므로, 해당 열에 대한 특별한 처리 생략
scientists_json_string = scientists.to_json(orient='records', indent=2)
print("DataFrame을 JSON 문자열로 변환 (처음 일부):")
print(scientists_json_string[:500] + "...") # 문자열의 일부만 출력하여 가독성 높임

DataFrame을 JSON 문자열로 변환 (처음 일부):
[
  {
    "Name":"Rosaline Franklin",
    "Born":"1920-07-25",
    "Died":"1958-04-16",
    "Age":37,
    "Occupation":"Chemist"
  },
  {
    "Name":"William Gosset",
    "Born":"1876-06-13",
    "Died":"1937-10-16",
    "Age":61,
    "Occupation":"Statistician"
  },
  {
    "Name":"Florence Nightingale",
    "Born":"1820-05-12",
    "Died":"1910-08-13",
    "Age":90,
    "Occupation":"Nurse"
  },
  {
    "Name":"Marie Curie",
    "Born":"1867-11-07",
    "Died":"1934-07-04",
    "Age":66,
    "...

In [47]:
# JSON 문자열을 데이터프레임으로 변환
loaded_scientists_json = pd.read_json(
    io.StringIO(scientists_json_string),
    orient='records'
)

# 'Born'과 'Died' 열이 문자열로 로드되었을 수 있으므로 datetime 객체로 다시 변환
loaded_scientists_json['Born'] = pd.to_datetime(loaded_scientists_json['Born'])
loaded_scientists_json['Died'] = pd.to_datetime(loaded_scientists_json['Died'])

print("\nJSON에서 불러온 데이터프레임 (처음 5개):")
display(loaded_scientists_json.head())

JSON에서 불러온 데이터프레임 (처음 5개):

                   Name       Born       Died  Age    Occupation
0     Rosaline Franklin 1920-07-25 1958-04-16   37       Chemist
1        William Gosset 1876-06-13 1937-10-16   61  Statistician
2  Florence Nightingale 1820-05-12 1910-08-13   90         Nurse
3           Marie Curie 1867-11-07 1934-07-04   66       Chemist
4         Rachel Carson 1907-05-27 1964-04-14   56     Biologist