In [34]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/kwukdt/data-analysis/data-collection/gapminder.tsv', sep='\t')

In [35]:
# 1. 데이터 구조 파악하기

# df.shape, df.columns, df.dtypes
print(f"(행, 열): {df.shape}")
print(f"열 이름 목록: {df.columns}")
print(f"\n--- 각 열의 자료형 ---\n{df.dtypes}")

# df.info()
print(f"\n--- 데이터 프레임 종합 정보 ---")
df.info()

# df.head()
print(f"\n--- 상위 5개 열 ---")
display(df.head())

# df.tail()
print(f"\n--- 하위 5개 열 ---")
display(df.tail())

(행, 열): (1704, 6)
열 이름 목록: Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

--- 각 열의 자료형 ---
country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

--- 데이터 프레임 종합 정보 ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   object
 1   continent  1704 non-null   object
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB

--- 상위 5개 열 ---

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

--- 하위 5개 열 ---

       country continent  year  lifeExp       pop   gdpPercap
1699  Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700  Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701  Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702  Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298

In [49]:
# 2. 데이터 추출 - 열(Column) 데이터 추출

# 시리즈(Series) 추출
country_df = df['country']
print("country_df의 자료형:", type(country_df))
display(country_df.head())

# 데이터 프레임(DataFrame) 추출 (리스트 활용)
subset = df[['country', 'continent', 'year']]
print("\nsubset의 자료형:", type(subset))
display(subset.head())

country_df의 자료형: <class 'pandas.core.series.Series'>

0    Afghanistan
1    Afghanistan
2    Afghanistan
3    Afghanistan
4    Afghanistan
Name: country, dtype: object

subset의 자료형: <class 'pandas.core.frame.DataFrame'>

       country continent  year
0  Afghanistan      Asia  1952
1  Afghanistan      Asia  1957
2  Afghanistan      Asia  1962
3  Afghanistan      Asia  1967
4  Afghanistan      Asia  1972

In [59]:
# 3. 데이터 추출 - 행(Row) 데이터 추출

# loc (Label-based) - 인덱스 값으로 추출
print("--- 인덱스 라벨이 0인 단일 행 ---")
display(df.loc[0])
print("\n--- 인덱스 라벨이 99인 단일 행 ---")
display(df.loc[99])
print("\n--- 인덱스 라벨이 0, 99, 999인 여러 행 ---")
display(df.loc[[0, 99, 999]])

# iloc (Integer-based) - 위치 번호로 추출
print("\n--- 가장 첫 번째 위치의 행(0번 위치) ---")
display(df.iloc[0])
print("\n--- 100번째 위치의 행(99번 위치) ---")
display(df.iloc[99])
print("\n--- 가장 마지막 위치의 행 ---")
display(df.iloc[-1])
print("\n--- 0, 99, 999번째 위치의 여러 행 ---")
display(df.iloc[[0, 99, 999]])

--- 인덱스 라벨이 0인 단일 행 ---

country      Afghanistan
continent           Asia
year                1952
lifeExp           28.801
pop              8425333
gdpPercap     779.445314
Name: 0, dtype: object

--- 인덱스 라벨이 99인 단일 행 ---

country      Bangladesh
continent          Asia
year               1967
lifeExp          43.453
pop            62821884
gdpPercap    721.186086
Name: 99, dtype: object

--- 인덱스 라벨이 0, 99, 999인 여러 행 ---

         country continent  year  lifeExp       pop    gdpPercap
0    Afghanistan      Asia  1952   28.801   8425333   779.445314
99    Bangladesh      Asia  1967   43.453  62821884   721.186086
999     Mongolia      Asia  1967   51.253   1149500  1226.041130

--- 가장 첫 번째 위치의 행(0번 위치) ---

country      Afghanistan
continent           Asia
year                1952
lifeExp           28.801
pop              8425333
gdpPercap     779.445314
Name: 0, dtype: object

--- 100번째 위치의 행(99번 위치) ---

country      Bangladesh
continent          Asia
year               1967
lifeExp          43.453
pop            62821884
gdpPercap    721.186086
Name: 99, dtype: object

--- 가장 마지막 위치의 행 ---

country        Zimbabwe
continent        Africa
year               2007
lifeExp          43.487
pop            12311143
gdpPercap    469.709298
Name: 1703, dtype: object

--- 0, 99, 999번째 위치의 여러 행 ---

         country continent  year  lifeExp       pop    gdpPercap
0    Afghanistan      Asia  1952   28.801   8425333   779.445314
99    Bangladesh      Asia  1967   43.453  62821884   721.186086
999     Mongolia      Asia  1967   51.253   1149500  1226.041130

In [58]:
# 4. 데이터 추출 - 행(Row)과 열(Column) 데이터 추출

# loc(Label-based)
print(f"인덱스 라벨이 42인 행의 'country' 열에 해당하는 값: {df.loc[42, 'country']}")
print("\n--- 인덱스 라벨이 0, 99, 999인 행들과 'country', 'lifeExp', 'gdpPercap' 열들에 해당하는 데이터 ---")
display(df.loc[[0, 99, 999], ['country', 'lifeExp', 'gdpPercap']])

# iloc(Integer-based)
print(f"\n42번째 위치의 행과 0번째 위치의 열에 해당하는 값: {df.iloc[42, 0]}")
print("\n--- 0, 99, 999번째 위치의 행들과 0, 3, 5번째 위치의 열들에 해당하는 데이터 ---")
display(df.iloc[[0, 99, 999], [0, 3, 5]])

인덱스 라벨이 42인 행의 'country' 열에 해당하는 값: Angola

--- 인덱스 라벨이 0, 99, 999인 행들과 'country', 'lifeExp', 'gdpPercap' 열들에 해당하는 데이터 ---

         country  lifeExp    gdpPercap
0    Afghanistan   28.801   779.445314
99    Bangladesh   43.453   721.186086
999     Mongolia   51.253  1226.041130

42번째 위치의 행과 0번째 위치의 열에 해당하는 값: Angola

--- 0, 99, 999번째 위치의 행들과 0, 3, 5번째 위치의 열들에 해당하는 데이터 ---

         country  lifeExp    gdpPercap
0    Afghanistan   28.801   779.445314
99    Bangladesh   43.453   721.186086
999     Mongolia   51.253  1226.041130

In [56]:
# 5. 데이터 추출 - 슬라이싱(Slicing)과 범위 지정

# iloc 슬라이싱
print("--- 모든 행에서 처음 3개 열 추출 (0, 1, 2번) ---")
display(df.iloc[:, :3].head())

# iloc 슬라이싱
print("\n--- 모든 행에서 3~5번 열 추출 (3, 4, 5번) ---")
display(df.iloc[:, 3:6].head())

# iloc 슬라이싱
print("\n--- 모든 행에서 짝수 번호 열만 추출 (0, 2, 4번) ---")
display(df.iloc[:, 0:6:2].head())

# loc 슬라이싱
print("\n--- 모든 행에서 'year', 'pop' 열 추출 ---")
display(df.loc[:, ['year', 'pop']].head())

# iloc와 range() 함수 활용
print("\n--- 처음 5개 열 (0, 1, 2, 3, 4) ---")
display(df.iloc[:, list(range(5))].head())

--- 모든 행에서 처음 3개 열 추출 (0, 1, 2번) ---

       country continent  year
0  Afghanistan      Asia  1952
1  Afghanistan      Asia  1957
2  Afghanistan      Asia  1962
3  Afghanistan      Asia  1967
4  Afghanistan      Asia  1972

--- 모든 행에서 3~5번 열 추출 (3, 4, 5번) ---

   lifeExp       pop   gdpPercap
0   28.801   8425333  779.445314
1   30.332   9240934  820.853030
2   31.997  10267083  853.100710
3   34.020  11537966  836.197138
4   36.088  13079460  739.981106

--- 모든 행에서 짝수 번호 열만 추출 (0, 2, 4번) ---

       country  year       pop
0  Afghanistan  1952   8425333
1  Afghanistan  1957   9240934
2  Afghanistan  1962  10267083
3  Afghanistan  1967  11537966
4  Afghanistan  1972  13079460

--- 모든 행에서 'year', 'pop' 열 추출 ---

   year       pop
0  1952   8425333
1  1957   9240934
2  1962  10267083
3  1967  11537966
4  1972  13079460

--- 처음 5개 열 (0, 1, 2, 3, 4) ---

       country continent  year  lifeExp       pop
0  Afghanistan      Asia  1952   28.801   8425333
1  Afghanistan      Asia  1957   30.332   9240934
2  Afghanistan      Asia  1962   31.997  10267083
3  Afghanistan      Asia  1967   34.020  11537966
4  Afghanistan      Asia  1972   36.088  13079460

In [54]:
# 6. 기초 통계 - 그룹화 (Groupby)

# 단일 열 그룹화
print("--- 연도별 기대수명 평균 ---")
display(df.groupby('year')['lifeExp'].mean().head())

# 다중 열 그룹화
print("\n--- 연도 + 대륙별 기대수명, GDP 평균 ---")
display(df.groupby(['year', 'continent'])[['lifeExp', 'gdpPercap']].mean().head())

# reset_index()
print("\n--- 계층 인덱스를 일반 열로 변환 ---")
display(df.groupby(['year', 'continent'])[['lifeExp', 'gdpPercap']].mean().reset_index().head())

--- 연도별 기대수명 평균 ---

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
Name: lifeExp, dtype: float64

--- 연도 + 대륙별 기대수명, GDP 평균 ---

                  lifeExp     gdpPercap
year continent
1952 Africa     39.135500   1252.572466
     Americas   53.279840   4079.062552
     Asia       46.314394   5195.484004
     Europe     64.408500   5661.057435
     Oceania    69.255000  10298.085650

--- 계층 인덱스를 일반 열로 변환 ---

   year continent    lifeExp     gdpPercap
0  1952    Africa  39.135500   1252.572466
1  1952  Americas  53.279840   4079.062552
2  1952      Asia  46.314394   5195.484004
3  1952    Europe  64.408500   5661.057435
4  1952   Oceania  69.255000  10298.085650

In [53]:
# 7. 기초 통계 - 고유 값 및 빈도 분석

# nunique()
print(f"--- 대륙별 국가 수(중복 제외) ---")
display(df.groupby('continent')['country'].nunique())

# value_counts()
print(f"\n--- 대륙별 데이터 행 수(빈도수) ---")
display(df['continent'].value_counts())

--- 대륙별 국가 수(중복 제외) ---

continent
Africa      52
Americas    25
Asia        33
Europe      30
Oceania      2
Name: country, dtype: int64

--- 대륙별 데이터 행 수(빈도수) ---

continent
Africa      624
Asia        396
Europe      360
Americas    300
Oceania      24
Name: count, dtype: int64