In [13]:
import numpy as np
import pandas as pd

In [14]:
s = pd.Series(data=['Wes McKinney', 'Creator of Pandas'], index=['Person', 'Who'])
display(s)

Person         Wes McKinney
Who       Creator of Pandas
dtype: object

In [15]:
scientist = pd.DataFrame({
    "Name": ["Rosaline Franklin", "William Gosset"],
    "Occupation": ["Chemist", "Statistician"],
    "Born": ["1920-07-25", "1876-06-13"],
    "Died": ["1958-04-16", "1937-10-16"],
    "Age": [37, 61],
},
  index=["Rosaline Franklin", "William Gosset"],
  columns=["Occupation", "Born", "Age", "Died"])
display(scientist)

                     Occupation        Born  Age        Died
Rosaline Franklin       Chemist  1920-07-25   37  1958-04-16
William Gosset     Statistician  1876-06-13   61  1937-10-16

In [16]:
first_row = scientist.loc['William Gosset']
print(type(first_row))
display(first_row)

<class 'pandas.core.series.Series'>

Occupation    Statistician
Born            1876-06-13
Age                     61
Died            1937-10-16
Name: William Gosset, dtype: object

In [17]:
print(first_row.index)
print(first_row.index[0])

Index(['Occupation', 'Born', 'Age', 'Died'], dtype='object')
Occupation

In [18]:
print(first_row.keys())
print(first_row.keys()[0])

Index(['Occupation', 'Born', 'Age', 'Died'], dtype='object')
Occupation

In [19]:
scientist = pd.read_csv("/content/drive/MyDrive/kwukdt/data-analysis/data-collection/scientists.csv")
display(scientist)

                   Name        Born        Died  Age          Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37             Chemist
1        William Gosset  1876-06-13  1937-10-16   61        Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90               Nurse
3           Marie Curie  1867-11-07  1934-07-04   66             Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56           Biologist
5             John Snow  1813-03-15  1858-06-16   45           Physician
6           Alan Turing  1912-06-23  1954-06-07   41  Computer Scientist
7          Johann Gauss  1777-04-30  1855-02-23   77       Mathematician

In [21]:
age = scientist['Age']

In [22]:
print(age.mean())

59.125

In [24]:
display(age[age > age.mean()])

1    61
2    90
3    66
7    77
Name: Age, dtype: int64

In [25]:
display(age + pd.Series([1, 100]))

0     38.0
1    161.0
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
7      NaN
dtype: float64